name: llm-env
channels:
- conda-forge
- defaults
dependencies:
  - python=3.10
  - ipykernel=6.25.2
  - pip:
    - numpy==1.26.0
    - pandas==2.1.1
    - mlflow[gateway]==2.7.1
    - langchain[all]==0.0.310